[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[context.production.environment]
  NODE_VERSION = "20.x"
  # Uncomment the next line if you need OpenSSL legacy provider
  # NODE_OPTIONS = "--openssl-legacy-provider"
